### ISSUE TITLE
File Searching 

### ISSUE THREAD

**Issue by DarkAxi0m** [hobigo/nextcloud-node-client#10]
seems nextcloud's webdav has a support for searching.
https://docs.nextcloud.com/server/16/developer_manual/client_apis/WebDAV/search.html

Is this implemented, or is there a way i can do manual webdav calls??

**Comment by hobigo** [comment]
the nextcloud-node-client is a wrapper of nextcloud apis.
This search functionality is based on WebDAV and is not (yet) wrapped in the client.
However this search functionality is more a select and not a fulltext search.

**Comment by DarkAxi0m** [comment]
Oh ok, i just assumed it was because the NCClient constructor needs for the webdav path.

**Comment by hobigo** [comment]
I close the issue and put the search functionality on my todo list
