### ISSUE TITLE
Compatibility with node 10

### ISSUE THREAD

**Issue by thomaslc66** [hobigo/nextcloud-node-client#11]
Hey is your library compatible with node 10 or more ?

I always have this error when i try to install it !

```
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
error nextcloud-node-client@0.3.1: The engine "node" is incompatible with this module. Expected version "8.x". Got "10.16.3"
error Found incompatible module.
```

Thank you

**Comment by thomaslc66** [comment]
Is this line on your package.json normal ?

`    "x@types/node": "^8.10.45"`

**Comment by hobigo** [comment]
Hi Thomas,
the line with "x@types/node": "^8.10.45" is wrong an can be deleted.
The the installation runs ok. Thanks

The current version has been tested with node 12 on windows 10 64.

**Comment by hobigo** [comment]
The installation problem is now fixed
npm i
npm test
