### ISSUE TITLE
create a share link of a file

### ISSUE THREAD

**Issue by fatshotty** [hobigo/nextcloud-node-client#12]
hello, i'm using your lib for the first time. I need to create share-link of a file but I cannot find API.
Is there a way to do that?

Thanks in advance.

**Describe the bug**
create share-link of a file

**To Reproduce**

**Expected behavior**
An API call to create share-link of the file

**Additional context**

**Comment by hobigo** [comment]
Hi fatshotty,
this api has not been wrapped into the library yet. 
I would put propose the following api with the most basic share to start with.

share:PublicShare = await file.createPublicShare();
doSomethingWith(share.url );

share:PublicShare = await folder.createPublicShare();
doSomethingWith(share.url );

Share: 
 url
 resource: file | folder

Would that help? When do you need it?

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-share-api.html

**Comment by fatshotty** [comment]
hi, thanks for reply.
I think your example code is very good. However Nextcloud gives the possibility to choose the "shareType": public, user, group. And also the expiration date.
Will it be possible to include those features?

Thanks again

**Comment by hobigo** [comment]
sure it is possible. 
However, user and group classes are the prerequisite for that.
This would take a bit longer

**Comment by fatshotty** [comment]
thanks.
My need, now, is only public-share. Hope this can help :)

thanks

**Comment by hobigo** [comment]
Hi,
new release 1.1.1 is available 
it contains now public shares

```typescript
   const file = await client.getFile("/products/MyFile.txt");
    // share the file (works also for folder)
    const createShare: ICreateShare = { fileSystemElement: file };
    const share: Share = await client.createShare(createShare);
    await share.setPassword("some password");
    await share.setNote("some note\nnew line");
    await share.setExpiration(new Date(2020, 11, 5));        
    await share.delete();
```

**Comment by fatshotty** [comment]
hi,
many thanks for new feature :)

one question:
` const share: Share = await client.createShare(createShare);`
Will this line create the 'public share' ? I mean:
with your example code I can create the 'share' resource and I can set password, note and expiration date. 
I just need a public link. Should I only use the 'createShare( )' method?

Thanks

**Comment by hobigo** [comment]
Hi,
thanks for the feedback.
I missed to document the most important part - the url. 
Use the url of the share object to get the link.

createShare creates a share object. The object contains the url.

```typescript
    const file = await client.getFile("/products/MyFile.txt");
    // share the file (works also for folder)
    const createShare: ICreateShare = { fileSystemElement: file };
    const share: Share = await client.createShare(createShare);
    // change share settings
    await share.setPassword("some password");
    await share.setNote("some note\nnew line");
    await share.setExpiration(new Date(2020, 11, 5));  
    // use the url to access the share 
    const shareLink:string = share.url;
    // delete share, if not required anymore
    await share.delete();
```

**Comment by fatshotty** [comment]
good job
thanks ;)

**Comment by fatshotty** [comment]
hi,
i'm trying to create a ShareLink as per your example.
It seems to work fine :)
I wonder: is there a way to get an already shared link for the same file?
I mean:
- I can create share link to file `/products/MyFile.txt` and obtain its link -> OK
- I need to read the share link (if exists) to file `/products/OtherFile.txt` 
   - in case it doesn't exist -> create a new one
   - in case it exists -> get the already existing share link

Thanks
