### ISSUE TITLE
Fuse/Merge with tentwentyfour/nextcloud-link ?

### ISSUE THREAD

**Issue by kwisatz** [hobigo/nextcloud-node-client#13]
Hi Holger,

just wanted to get in touch with you – and this is the only way we found – to discuss a possible collaboration and possibly the route to a merger of nextcloud-node-client and https://github.com/tentwentyfour/nextcloud-link

We might be able to get there faster if we collaborate, rather than building the same thing twice. If you're interested, let's discuss specifics. Get in touch with us a hello {at} tentwentyfour.lu (DE/EN)

**Comment by hobigo** [comment]
Hi David,
the scope of the projects seem to be very similar. Here are some of my thoughts.

However, the APIs are very different. My understanding is, that nextcloud link provides a functional API to nextcloud resources. And it seems that the nextcloud concepts and technical concepts like (webddav, OCS) are exposed. The API should cover the all the nextcloud functionality.

The nextcloud-node-client uses a object oriented API ( not better, but different - a matter of taste) and tries to wrap the nextcloud concepts. It is also not intended to expose all nextcloud  functions.

The design of the nextcloud-node-client uses only one HTTP client to ensure offline testability (OCS and WebDav) from the beginning.
The 100 tests can be recorded and replayed offline within 2 seconds. This ensures a high code coverage and can uncover incompatible API changes on nextcloud side.

The nextcloud-node-client is currently not very much used in the wild.
I would propose to stay in contact. I can learn a lot from your implementation. 
And the diversity of API concepts may help the community. 

Regards Holger

**Comment by hobigo** [comment]
closing the issue
